/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import attrsManager from '../../common/AttrsManager'
import router from '@ohos.router'

class AlphabetIndexerModifier implements AttributeModifier<AlphabetIndexerAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: AlphabetIndexerAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class BadgeModifier implements AttributeModifier<BadgeAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: BadgeAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class ButtonModifier implements AttributeModifier<ButtonAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: ButtonAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class BlankModifier implements AttributeModifier<BlankAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: BlankAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class CalendarPickerModifier implements AttributeModifier<CalendarPickerAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: CalendarPickerAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class CanvasModifier implements AttributeModifier<CanvasAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: CanvasAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class CheckboxModifier implements AttributeModifier<CheckboxAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: CheckboxAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class CheckboxGroupModifier implements AttributeModifier<CheckboxGroupAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: CheckboxGroupAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class CircleModifier implements AttributeModifier<CircleAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: CircleAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class ColumnModifier implements AttributeModifier<ColumnAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: ColumnAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class ColumnSplitModifier implements AttributeModifier<ColumnSplitAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: ColumnSplitAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class CounterModifier implements AttributeModifier<CounterAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: CounterAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class DataPanelModifier implements AttributeModifier<DataPanelAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: DataPanelAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class DatePickerModifier implements AttributeModifier<DatePickerAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: DatePickerAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class DividerModifier implements AttributeModifier<DividerAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: DividerAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class EllipseModifier implements AttributeModifier<EllipseAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: EllipseAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class FlexModifier implements AttributeModifier<FlexAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: FlexAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class FlowItemModifier implements AttributeModifier<FlowItemAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: FlowItemAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class FormLinkModifier implements AttributeModifier<FormLinkAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: FormLinkAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class GaugeModifier implements AttributeModifier<GaugeAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: GaugeAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class GridModifier implements AttributeModifier<GridAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: GridAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class GridColModifier implements AttributeModifier<GridColAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: GridColAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class GridItemModifier implements AttributeModifier<GridItemAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: GridItemAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class GridRowModifier implements AttributeModifier<GridRowAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: GridRowAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class HyperlinkModifier implements AttributeModifier<HyperlinkAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: HyperlinkAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class ImageModifier implements AttributeModifier<ImageAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: ImageAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class ImageAnimatorModifier implements AttributeModifier<ImageAnimatorAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: ImageAnimatorAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class LineModifier implements AttributeModifier<LineAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: LineAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class ListModifier implements AttributeModifier<ListAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: ListAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class ListItemModifier implements AttributeModifier<ListItemAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: ListItemAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class ListItemGroupModifier implements AttributeModifier<ListItemGroupAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: ListItemGroupAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class LoadingProgressModifier implements AttributeModifier<LoadingProgressAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: LoadingProgressAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class MarqueeModifier implements AttributeModifier<MarqueeAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: MarqueeAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class MenuModifier implements AttributeModifier<MenuAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: MenuAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class MenuItemModifier implements AttributeModifier<MenuItemAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: MenuItemAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class MenuItemGroupModifier implements AttributeModifier<MenuItemGroupAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: MenuItemGroupAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class NavDestinationModifier implements AttributeModifier<NavDestinationAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: NavDestinationAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class NavigationModifier implements AttributeModifier<NavigationAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: NavigationAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class NavigatorModifier implements AttributeModifier<NavigatorAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: NavigatorAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class NavRouterModifier implements AttributeModifier<NavRouterAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: NavRouterAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class PanelModifier implements AttributeModifier<PanelAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: PanelAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class PathModifier implements AttributeModifier<PathAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: PathAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class PolygonModifier implements AttributeModifier<PolygonAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: PolygonAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class PolylineModifier implements AttributeModifier<PolylineAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: PolylineAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class ProgressModifier implements AttributeModifier<ProgressAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: ProgressAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class QRCodeModifier implements AttributeModifier<QRCodeAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: QRCodeAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class RadioModifier implements AttributeModifier<RadioAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: RadioAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class RatingModifier implements AttributeModifier<RatingAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: RatingAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class RectModifier implements AttributeModifier<RectAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: RectAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class RefreshModifier implements AttributeModifier<RefreshAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: RefreshAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class RelativeContainerModifier implements AttributeModifier<RelativeContainerAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: RelativeContainerAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class RemoteWindowModifier implements AttributeModifier<RemoteWindowAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: RemoteWindowAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class RichEditorModifier implements AttributeModifier<RichEditorAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: RichEditorAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class RichTextModifier implements AttributeModifier<RichTextAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: RichTextAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class RowModifier implements AttributeModifier<RowAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: RowAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class RowSplitModifier implements AttributeModifier<RowSplitAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: RowSplitAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class ScrollModifier implements AttributeModifier<ScrollAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: ScrollAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class ScrollBarModifier implements AttributeModifier<ScrollBarAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: ScrollBarAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class SearchModifier implements AttributeModifier<SearchAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: SearchAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class SelectModifier implements AttributeModifier<SelectAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: SelectAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class ShapeModifier implements AttributeModifier<ShapeAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: ShapeAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class SideBarContainerModifier implements AttributeModifier<SideBarContainerAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: SideBarContainerAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class SliderModifier implements AttributeModifier<SliderAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: SliderAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class SpanModifier implements AttributeModifier<SpanAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: SpanAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class StackModifier implements AttributeModifier<StackAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: StackAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class StepperModifier implements AttributeModifier<StepperAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: StepperAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class StepperItemModifier implements AttributeModifier<StepperItemAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: StepperItemAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class SwiperModifier implements AttributeModifier<SwiperAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: SwiperAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class TabContentModifier implements AttributeModifier<TabContentAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: TabContentAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class TabsModifier implements AttributeModifier<TabsAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: TabsAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class TextModifier implements AttributeModifier<TextAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: TextAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class TextAreaModifier implements AttributeModifier<TextAreaAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: TextAreaAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class TextClockModifier implements AttributeModifier<TextClockAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: TextClockAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class TextInputModifier implements AttributeModifier<TextInputAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: TextInputAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class TextPickerModifier implements AttributeModifier<TextPickerAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: TextPickerAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class TextTimerModifier implements AttributeModifier<TextTimerAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: TextTimerAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class TimePickerModifier implements AttributeModifier<TimePickerAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: TimePickerAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class ToggleModifier implements AttributeModifier<ToggleAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: ToggleAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class VideoModifier implements AttributeModifier<VideoAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: VideoAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class WaterFlowModifier implements AttributeModifier<WaterFlowAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: WaterFlowAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class WebModifier implements AttributeModifier<WebAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: WebAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class WindowSceneModifier implements AttributeModifier<WindowSceneAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: WindowSceneAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

class XComponentModifier implements AttributeModifier<XComponentAttribute> {
	mBlendMode: BlendMode = BlendMode.COLOR_DODGE;

	applyNormalAttribute(instance: XComponentAttribute): void {
		instance.blendMode(this.mBlendMode)
	}
}

@Entry
@Component
struct BlendModePage {
	@State _blendModeAlphabetIndexerModifier: AlphabetIndexerModifier = new AlphabetIndexerModifier()
	@State _blendModeBadgeModifier: BadgeModifier = new BadgeModifier()
	@State _blendModeButtonModifier: ButtonModifier = new ButtonModifier()
	@State _blendModeBlankModifier: BlankModifier = new BlankModifier()
	@State _blendModeCalendarPickerModifier: CalendarPickerModifier = new CalendarPickerModifier()
	@State _blendModeCanvasModifier: CanvasModifier = new CanvasModifier()
	@State _blendModeCheckboxModifier: CheckboxModifier = new CheckboxModifier()
	@State _blendModeCheckboxGroupModifier: CheckboxGroupModifier = new CheckboxGroupModifier()
	@State _blendModeCircleModifier: CircleModifier = new CircleModifier()
	@State _blendModeColumnModifier: ColumnModifier = new ColumnModifier()
	@State _blendModeColumnSplitModifier: ColumnSplitModifier = new ColumnSplitModifier()
	@State _blendModeCounterModifier: CounterModifier = new CounterModifier()
	@State _blendModeDataPanelModifier: DataPanelModifier = new DataPanelModifier()
	@State _blendModeDatePickerModifier: DatePickerModifier = new DatePickerModifier()
	@State _blendModeDividerModifier: DividerModifier = new DividerModifier()
	@State _blendModeEllipseModifier: EllipseModifier = new EllipseModifier()
	@State _blendModeFlexModifier: FlexModifier = new FlexModifier()
	@State _blendModeFlowItemModifier: FlowItemModifier = new FlowItemModifier()
	@State _blendModeFormLinkModifier: FormLinkModifier = new FormLinkModifier()
	@State _blendModeGaugeModifier: GaugeModifier = new GaugeModifier()
	@State _blendModeGridModifier: GridModifier = new GridModifier()
	@State _blendModeGridColModifier: GridColModifier = new GridColModifier()
	@State _blendModeGridItemModifier: GridItemModifier = new GridItemModifier()
	@State _blendModeGridRowModifier: GridRowModifier = new GridRowModifier()
	@State _blendModeHyperlinkModifier: HyperlinkModifier = new HyperlinkModifier()
	@State _blendModeImageModifier: ImageModifier = new ImageModifier()
	@State _blendModeImageAnimatorModifier: ImageAnimatorModifier = new ImageAnimatorModifier()
	@State _blendModeLineModifier: LineModifier = new LineModifier()
	@State _blendModeListModifier: ListModifier = new ListModifier()
	@State _blendModeListItemModifier: ListItemModifier = new ListItemModifier()
	@State _blendModeListItemGroupModifier: ListItemGroupModifier = new ListItemGroupModifier()
	@State _blendModeLoadingProgressModifier: LoadingProgressModifier = new LoadingProgressModifier()
	@State _blendModeMarqueeModifier: MarqueeModifier = new MarqueeModifier()
	@State _blendModeMenuModifier: MenuModifier = new MenuModifier()
	@State _blendModeMenuItemModifier: MenuItemModifier = new MenuItemModifier()
	@State _blendModeMenuItemGroupModifier: MenuItemGroupModifier = new MenuItemGroupModifier()
	@State _blendModeNavDestinationModifier: NavDestinationModifier = new NavDestinationModifier()
	@State _blendModeNavigationModifier: NavigationModifier = new NavigationModifier()
	@State _blendModeNavigatorModifier: NavigatorModifier = new NavigatorModifier()
	@State _blendModeNavRouterModifier: NavRouterModifier = new NavRouterModifier()
	@State _blendModePanelModifier: PanelModifier = new PanelModifier()
	@State _blendModePathModifier: PathModifier = new PathModifier()
	@State _blendModePolygonModifier: PolygonModifier = new PolygonModifier()
	@State _blendModePolylineModifier: PolylineModifier = new PolylineModifier()
	@State _blendModeProgressModifier: ProgressModifier = new ProgressModifier()
	@State _blendModeQRCodeModifier: QRCodeModifier = new QRCodeModifier()
	@State _blendModeRadioModifier: RadioModifier = new RadioModifier()
	@State _blendModeRatingModifier: RatingModifier = new RatingModifier()
	@State _blendModeRectModifier: RectModifier = new RectModifier()
	@State _blendModeRefreshModifier: RefreshModifier = new RefreshModifier()
	@State _blendModeRelativeContainerModifier: RelativeContainerModifier = new RelativeContainerModifier()
	@State _blendModeRemoteWindowModifier: RemoteWindowModifier = new RemoteWindowModifier()
	@State _blendModeRichEditorModifier: RichEditorModifier = new RichEditorModifier()
	@State _blendModeRichTextModifier: RichTextModifier = new RichTextModifier()
	@State _blendModeRowModifier: RowModifier = new RowModifier()
	@State _blendModeRowSplitModifier: RowSplitModifier = new RowSplitModifier()
	@State _blendModeScrollModifier: ScrollModifier = new ScrollModifier()
	@State _blendModeScrollBarModifier: ScrollBarModifier = new ScrollBarModifier()
	@State _blendModeSearchModifier: SearchModifier = new SearchModifier()
	@State _blendModeSelectModifier: SelectModifier = new SelectModifier()
	@State _blendModeShapeModifier: ShapeModifier = new ShapeModifier()
	@State _blendModeSideBarContainerModifier: SideBarContainerModifier = new SideBarContainerModifier()
	@State _blendModeSliderModifier: SliderModifier = new SliderModifier()
	@State _blendModeSpanModifier: SpanModifier = new SpanModifier()
	@State _blendModeStackModifier: StackModifier = new StackModifier()
	@State _blendModeStepperModifier: StepperModifier = new StepperModifier()
	@State _blendModeStepperItemModifier: StepperItemModifier = new StepperItemModifier()
	@State _blendModeSwiperModifier: SwiperModifier = new SwiperModifier()
	@State _blendModeTabContentModifier: TabContentModifier = new TabContentModifier()
	@State _blendModeTabsModifier: TabsModifier = new TabsModifier()
	@State _blendModeTextModifier: TextModifier = new TextModifier()
	@State _blendModeTextAreaModifier: TextAreaModifier = new TextAreaModifier()
	@State _blendModeTextClockModifier: TextClockModifier = new TextClockModifier()
	@State _blendModeTextInputModifier: TextInputModifier = new TextInputModifier()
	@State _blendModeTextPickerModifier: TextPickerModifier = new TextPickerModifier()
	@State _blendModeTextTimerModifier: TextTimerModifier = new TextTimerModifier()
	@State _blendModeTimePickerModifier: TimePickerModifier = new TimePickerModifier()
	@State _blendModeToggleModifier: ToggleModifier = new ToggleModifier()
	@State _blendModeVideoModifier: VideoModifier = new VideoModifier()
	@State _blendModeWaterFlowModifier: WaterFlowModifier = new WaterFlowModifier()
	@State _blendModeWebModifier: WebModifier = new WebModifier()
	@State _blendModeWindowSceneModifier: WindowSceneModifier = new WindowSceneModifier()
	@State _blendModeXComponentModifier: XComponentModifier = new XComponentModifier()
	@State targetView: string = router.getParams() ? router.getParams()['view']['targetView'] : ''
	@State componentKey: string = router.getParams() ? router.getParams()['view']['componentKey'] : ''
	@State parentWidth: number = router.getParams() ? router.getParams()['view']['parentWidth'] : 0
	@State parentHeight: number = router.getParams() ? router.getParams()['view']['parentHeight'] : 0
	@State columns: number = router.getParams() ? router.getParams()['view']['columns'] : 0
	@State gutter: number = router.getParams() ? router.getParams()['view']['gutter'] : 0
	@State parentBackGroundColor: string = router.getParams() ? router.getParams()['view']['parentBackGroundColor'] : '#FFFF00'
	@State parentComponentKey: string = router.getParams() ? router.getParams()['view']['parentComponentKey'] : ''

	onPageShow() {
		console.info('blendMode translate page show called ')
		attrsManager.registerDataChange(value => {
			console.info('blendMode [registerDataChange] ' + JSON.stringify(value.blendMode))
			this._blendModeAlphabetIndexerModifier.mBlendMode = value.blendMode
			this._blendModeBadgeModifier.mBlendMode = value.blendMode
			this._blendModeButtonModifier.mBlendMode = value.blendMode
			this._blendModeBlankModifier.mBlendMode = value.blendMode
			this._blendModeCalendarPickerModifier.mBlendMode = value.blendMode
			this._blendModeCanvasModifier.mBlendMode = value.blendMode
			this._blendModeCheckboxModifier.mBlendMode = value.blendMode
			this._blendModeCheckboxGroupModifier.mBlendMode = value.blendMode
			this._blendModeCircleModifier.mBlendMode = value.blendMode
			this._blendModeColumnModifier.mBlendMode = value.blendMode
			this._blendModeColumnSplitModifier.mBlendMode = value.blendMode
			this._blendModeCounterModifier.mBlendMode = value.blendMode
			this._blendModeDataPanelModifier.mBlendMode = value.blendMode
			this._blendModeDatePickerModifier.mBlendMode = value.blendMode
			this._blendModeDividerModifier.mBlendMode = value.blendMode
			this._blendModeEllipseModifier.mBlendMode = value.blendMode
			this._blendModeFlexModifier.mBlendMode = value.blendMode
			this._blendModeFlowItemModifier.mBlendMode = value.blendMode
			this._blendModeFormLinkModifier.mBlendMode = value.blendMode
			this._blendModeGaugeModifier.mBlendMode = value.blendMode
			this._blendModeGridModifier.mBlendMode = value.blendMode
			this._blendModeGridColModifier.mBlendMode = value.blendMode
			this._blendModeGridItemModifier.mBlendMode = value.blendMode
			this._blendModeGridRowModifier.mBlendMode = value.blendMode
			this._blendModeHyperlinkModifier.mBlendMode = value.blendMode
			this._blendModeImageModifier.mBlendMode = value.blendMode
			this._blendModeImageAnimatorModifier.mBlendMode = value.blendMode
			this._blendModeLineModifier.mBlendMode = value.blendMode
			this._blendModeListModifier.mBlendMode = value.blendMode
			this._blendModeListItemModifier.mBlendMode = value.blendMode
			this._blendModeListItemGroupModifier.mBlendMode = value.blendMode
			this._blendModeLoadingProgressModifier.mBlendMode = value.blendMode
			this._blendModeMarqueeModifier.mBlendMode = value.blendMode
			this._blendModeMenuModifier.mBlendMode = value.blendMode
			this._blendModeMenuItemModifier.mBlendMode = value.blendMode
			this._blendModeMenuItemGroupModifier.mBlendMode = value.blendMode
			this._blendModeNavDestinationModifier.mBlendMode = value.blendMode
			this._blendModeNavigationModifier.mBlendMode = value.blendMode
			this._blendModeNavigatorModifier.mBlendMode = value.blendMode
			this._blendModeNavRouterModifier.mBlendMode = value.blendMode
			this._blendModePanelModifier.mBlendMode = value.blendMode
			this._blendModePathModifier.mBlendMode = value.blendMode
			this._blendModePolygonModifier.mBlendMode = value.blendMode
			this._blendModePolylineModifier.mBlendMode = value.blendMode
			this._blendModeProgressModifier.mBlendMode = value.blendMode
			this._blendModeQRCodeModifier.mBlendMode = value.blendMode
			this._blendModeRadioModifier.mBlendMode = value.blendMode
			this._blendModeRatingModifier.mBlendMode = value.blendMode
			this._blendModeRectModifier.mBlendMode = value.blendMode
			this._blendModeRefreshModifier.mBlendMode = value.blendMode
			this._blendModeRelativeContainerModifier.mBlendMode = value.blendMode
			this._blendModeRemoteWindowModifier.mBlendMode = value.blendMode
			this._blendModeRichEditorModifier.mBlendMode = value.blendMode
			this._blendModeRichTextModifier.mBlendMode = value.blendMode
			this._blendModeRowModifier.mBlendMode = value.blendMode
			this._blendModeRowSplitModifier.mBlendMode = value.blendMode
			this._blendModeScrollModifier.mBlendMode = value.blendMode
			this._blendModeScrollBarModifier.mBlendMode = value.blendMode
			this._blendModeSearchModifier.mBlendMode = value.blendMode
			this._blendModeSelectModifier.mBlendMode = value.blendMode
			this._blendModeShapeModifier.mBlendMode = value.blendMode
			this._blendModeSideBarContainerModifier.mBlendMode = value.blendMode
			this._blendModeSliderModifier.mBlendMode = value.blendMode
			this._blendModeSpanModifier.mBlendMode = value.blendMode
			this._blendModeStackModifier.mBlendMode = value.blendMode
			this._blendModeStepperModifier.mBlendMode = value.blendMode
			this._blendModeStepperItemModifier.mBlendMode = value.blendMode
			this._blendModeSwiperModifier.mBlendMode = value.blendMode
			this._blendModeTabContentModifier.mBlendMode = value.blendMode
			this._blendModeTabsModifier.mBlendMode = value.blendMode
			this._blendModeTextModifier.mBlendMode = value.blendMode
			this._blendModeTextAreaModifier.mBlendMode = value.blendMode
			this._blendModeTextClockModifier.mBlendMode = value.blendMode
			this._blendModeTextInputModifier.mBlendMode = value.blendMode
			this._blendModeTextPickerModifier.mBlendMode = value.blendMode
			this._blendModeTextTimerModifier.mBlendMode = value.blendMode
			this._blendModeTimePickerModifier.mBlendMode = value.blendMode
			this._blendModeToggleModifier.mBlendMode = value.blendMode
			this._blendModeVideoModifier.mBlendMode = value.blendMode
			this._blendModeWaterFlowModifier.mBlendMode = value.blendMode
			this._blendModeWebModifier.mBlendMode = value.blendMode
			this._blendModeWindowSceneModifier.mBlendMode = value.blendMode
			this._blendModeXComponentModifier.mBlendMode = value.blendMode
		})
	}

	@Styles
  commonStyle() {
		.key(this.componentKey)
  }

	build() {
		Column() {
			if (this.targetView == 'AlphabetIndexer') {
				AlphabetIndexer({ arrayValue: ['#', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], selected: 0 })
					.commonStyle()
					.attributeModifier(this._blendModeAlphabetIndexerModifier)
			}
			if (this.targetView == 'Button') {
				Button('button1')
					.commonStyle()
					.attributeModifier(this._blendModeButtonModifier)
			}
			if (this.targetView == 'Blank') {
				Blank()
					.backgroundColor(Color.Yellow)
					.commonStyle()
					.attributeModifier(this._blendModeBlankModifier)
			}
			if (this.targetView == 'Checkbox') {
				Checkbox()
					.commonStyle()
					.attributeModifier(this._blendModeCheckboxModifier)
			}
			if (this.targetView == 'CheckboxGroup') {
				CheckboxGroup({ group: 'checkboxGroup' })
					.commonStyle()
					.attributeModifier(this._blendModeCheckboxGroupModifier)
			}
			if (this.targetView == 'DataPanel') {
				DataPanel({ values: [5, 10, 10, 7, 9, 10, 10, 10, 10] })
					.commonStyle()
					.attributeModifier(this._blendModeDataPanelModifier)
			}
			if (this.targetView == 'DatePicker') {
				DatePicker({ start: new Date('1970-1-1'), end: new Date('2100-1-1') })
					.commonStyle()
					.attributeModifier(this._blendModeDatePickerModifier)
			}
			if (this.targetView == 'Divider') {
				Divider()
					.commonStyle()
					.attributeModifier(this._blendModeDividerModifier)
			}
			if (this.targetView == 'Gauge') {
				Gauge({ value: 105 })
					.colors([[0x317AF7, 1], [0x5BA854, 1], [0xE08C3A, 1], [0x9C554B, 1]])
					.commonStyle()
					.attributeModifier(this._blendModeGaugeModifier)
			}
			if (this.targetView == 'Image') {
				Image($r('app.media.icon'))
					.commonStyle()
					.attributeModifier(this._blendModeImageModifier)
			}
			if (this.targetView == 'ImageAnimator') {
				ImageAnimator()
					.images([{ src: $r('app.media.icon') }])
					.commonStyle()
					.attributeModifier(this._blendModeImageAnimatorModifier)
			}
			if (this.targetView == 'LoadingProgress') {
				LoadingProgress()
					.commonStyle()
					.attributeModifier(this._blendModeLoadingProgressModifier)
			}
			if (this.targetView == 'Marquee') {
				Marquee({ 
					start: true,
					step: 50,
					loop: Infinity,
					fromStart: true,
					src: 'Running Marquee starts rolling'
				})
					.commonStyle()
					.attributeModifier(this._blendModeMarqueeModifier)
			}
			if (this.targetView == 'Navigation') {
				Navigation() {
				}
					.commonStyle()
					.attributeModifier(this._blendModeNavigationModifier)
			}
			if (this.targetView == 'Menu') {
				Menu() {
					MenuItem({ startIcon: $r('app.media.icon'), content: 'Menu' })
				}
					.backgroundColor(Color.Yellow)
					.commonStyle()
					.attributeModifier(this._blendModeMenuModifier)
			}
			if (this.targetView == 'NavRouter') {
				NavRouter() {
					Row() {
						Image($r('app.media.icon'))
					}

					NavDestination() {
						Text('NavDestination')
							.fontSize(10)
					}
				}
					.commonStyle()
					.attributeModifier(this._blendModeNavRouterModifier)
			}
			if (this.targetView == 'Progress') {
				Progress({ value: 10, type: ProgressType.Eclipse })
					.commonStyle()
					.attributeModifier(this._blendModeProgressModifier)
			}
			if (this.targetView == 'QRCode') {
				QRCode('Running Marquee starts rolling')
					.commonStyle()
					.attributeModifier(this._blendModeQRCodeModifier)
			}
			if (this.targetView == 'Radio') {
				Radio({ value: 'Radio1', group: 'radioGroup' })
					.commonStyle()
					.attributeModifier(this._blendModeRadioModifier)
			}
			if (this.targetView == 'Rating') {
				Rating({ rating: 3.5, indicator: false })
					.commonStyle()
					.attributeModifier(this._blendModeRatingModifier)
			}
			if (this.targetView == 'ScrollBar') {
				ScrollBar({ scroller: new Scroller(), state: BarState.On }) {
					Text()
						.width(20)
						.height(100)
						.borderRadius(10)
						.backgroundColor('#C0C0C0')
				}
					.commonStyle()
					.attributeModifier(this._blendModeScrollBarModifier)
			}
			if (this.targetView == 'Search') {
				Search()
					.commonStyle()
					.attributeModifier(this._blendModeSearchModifier)
			}
			if (this.targetView == 'Select') {
				Select([{ value: 'aaa' }, { value: 'bbb' }])
					.commonStyle()
					.attributeModifier(this._blendModeSelectModifier)
			}
			if (this.targetView == 'Slider') {
				Slider({ value: 50, min: 0, max: 100, style: SliderStyle.OutSet })
					.showTips(true)
					.commonStyle()
					.attributeModifier(this._blendModeSliderModifier)
			}
			if (this.targetView == 'Stepper') {
				Stepper() {
					StepperItem() {
						Column() {
							Text('Page One')
						}
					}
				}
					.commonStyle()
					.attributeModifier(this._blendModeStepperModifier)
			}
			if (this.targetView == 'StepperItem') {
				Stepper() {
					StepperItem() {
						Column() {
							Text('Page One')
						}
					}
						.backgroundColor(Color.Red)
						.commonStyle()
						.attributeModifier(this._blendModeStepperItemModifier)
				}
					.backgroundColor(Color.Yellow)
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'Text') {
				Text('text1')
					.commonStyle()
					.attributeModifier(this._blendModeTextModifier)
			}
			if (this.targetView == 'TextArea') {
				TextArea({ placeholder: 'The text area can hold an unlimited amount of text. input your word...' })
					.commonStyle()
					.attributeModifier(this._blendModeTextAreaModifier)
			}
			if (this.targetView == 'TextClock') {
				TextClock({ timeZoneOffset: -8 })
					.format('hms')
					.commonStyle()
					.attributeModifier(this._blendModeTextClockModifier)
			}
			if (this.targetView == 'TextInput') {
				TextInput({ placeholder: 'input your word...' })
					.commonStyle()
					.attributeModifier(this._blendModeTextInputModifier)
			}
			if (this.targetView == 'TextPicker') {
				TextPicker({ range: ['#', 'A', 'B', 'C', 'D', 'E', 'F', 'G'] })
					.commonStyle()
					.attributeModifier(this._blendModeTextPickerModifier)
			}
			if (this.targetView == 'TextTimer') {
				TextTimer({ isCountDown: true, count: 30000 })
					.format('mm:ss.SS')
					.fontColor(Color.Black)
					.commonStyle()
					.attributeModifier(this._blendModeTextTimerModifier)
			}
			if (this.targetView == 'TimePicker') {
				TimePicker({ selected: new Date('2022-07-22T08:00:00') })
					.commonStyle()
					.attributeModifier(this._blendModeTimePickerModifier)
			}
			if (this.targetView == 'Toggle') {
				Toggle({ type: ToggleType.Switch, isOn: false })
					.commonStyle()
					.attributeModifier(this._blendModeToggleModifier)
			}
			if (this.targetView == 'Web') {
				Web({ src: 'www.example.com', controller: new WebController() })
					.commonStyle()
					.attributeModifier(this._blendModeWebModifier)
			}
			if (this.targetView == 'Circle') {
				Circle()
					.width(150)
					.height(200)
					.commonStyle()
					.attributeModifier(this._blendModeCircleModifier)
			}
			if (this.targetView == 'Ellipse') {
				Ellipse()
					.commonStyle()
					.attributeModifier(this._blendModeEllipseModifier)
			}
			if (this.targetView == 'Line') {
				Line()
					.startPoint([0, 0])
					.endPoint([50, 100])
					.backgroundColor(Color.Black)
					.commonStyle()
					.attributeModifier(this._blendModeLineModifier)
			}
			if (this.targetView == 'Polyline') {
				Polyline()
					.commonStyle()
					.attributeModifier(this._blendModePolylineModifier)
			}
			if (this.targetView == 'Polygon') {
				Polygon()
					.commonStyle()
					.attributeModifier(this._blendModePolygonModifier)
			}
			if (this.targetView == 'Path') {
				Path()
					.commonStyle()
					.attributeModifier(this._blendModePathModifier)
			}
			if (this.targetView == 'Rect') {
				Rect()
					.commonStyle()
					.attributeModifier(this._blendModeRectModifier)
			}
			if (this.targetView == 'Shape') {
				Shape() {
					Rect()
						.width(100)
						.height(50)
				}
					.commonStyle()
					.attributeModifier(this._blendModeShapeModifier)
			}
			if (this.targetView == 'Badge') {
				Badge({ count: 50, style: { color: 0xFFFFFF, fontSize: 16, badgeSize: 20, badgeColor: Color.Red } }) {
					Button('message')
						.width(100)
						.height(50)
						.backgroundColor(0x317aff)
				}
					.commonStyle()
					.attributeModifier(this._blendModeBadgeModifier)
			}
			if (this.targetView == 'Column') {
				Column() {
					Button()
						.width(100)
						.height(50)
				}
					.commonStyle()
					.attributeModifier(this._blendModeColumnModifier)
			}
			if (this.targetView == 'ColumnSplit') {
				ColumnSplit() {
					Text('1')
						.width('100%')
						.height(50)
						.backgroundColor(0xF5DEB3)
						.textAlign(TextAlign.Center)
				}
					.commonStyle()
					.attributeModifier(this._blendModeColumnSplitModifier)
			}
			if (this.targetView == 'Counter') {
				Counter() {
				}
					.commonStyle()
					.attributeModifier(this._blendModeCounterModifier)
			}
			if (this.targetView == 'Flex') {
				Flex() {
					Text('1')
						.width('20%')
						.height(50)
						.backgroundColor(0xF5DEB3)
				}
					.commonStyle()
					.attributeModifier(this._blendModeFlexModifier)
			}
			if (this.targetView == 'GridRow') {
				GridRow({ columns: 1, direction: GridRowDirection.Row }) {
					ForEach(
						[Color.Red, Color.Orange, Color.Yellow, Color.Green, Color.Pink, Color.Grey, Color.Blue, Color.Brown],
						(color) => {
							GridCol({ span: { xs: 1, sm: 2, md: 3, lg: 4 } }) {
								Row()
									.width('100%')
									.height('20vp')
							}
								.borderColor(color)
								.borderWidth(2)
						}
					)
				}
					.commonStyle()
					.attributeModifier(this._blendModeGridRowModifier)
			}
			if (this.targetView == 'Grid') {
				Grid() {
					ForEach(['0', '1', '2', '3', '4'], () => {
						ForEach(['0', '1', '2', '3', '4'], (day: string) => {
							GridItem() {
								Text(day)
									.backgroundColor(Color.White)
									.width('100%')
									.height('100%')
									.textAlign(TextAlign.Center)
							}
						})
					})
				}
					.columnsTemplate('1fr 1fr 1fr 1fr 1fr')
					.rowsTemplate('1fr 1fr 1fr 1fr 1fr')
					.backgroundColor(0xFAEEE0)
					.commonStyle()
					.attributeModifier(this._blendModeGridModifier)
			}
			if (this.targetView == 'List') {
				List() {
				}
					.height('100%')
					.width('100%')
					.commonStyle()
					.attributeModifier(this._blendModeListModifier)
			}
			if (this.targetView == 'ListItem') {
				List({ space: 20, initialIndex: 0 }) {
					ListItem() {
						Text('item1')
							.width('100%')
							.textAlign(TextAlign.Center)
							.backgroundColor(Color.White)
					}
						.commonStyle()
						.attributeModifier(this._blendModeListItemModifier)
				}
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'ListItemGroup') {
				List({ space: 0, initialIndex: 0 }) {
					ListItemGroup()
						.backgroundColor(Color.Yellow)
						.commonStyle()
						.attributeModifier(this._blendModeListItemGroupModifier)
				}
					.backgroundColor(Color.Pink)
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'Navigator') {
				Navigator() {
					Text('Go to back page')
						.width('100%')
						.height(20)
				}
					.backgroundColor(Color.Red)
					.commonStyle()
					.attributeModifier(this._blendModeNavigatorModifier)
			}
			if (this.targetView == 'Panel') {
				Panel(true) {
					Text('Text')
				}
					.backgroundColor(Color.Yellow)
					.commonStyle()
					.attributeModifier(this._blendModePanelModifier)
			}
			if (this.targetView == 'Refresh') {
				Refresh({ refreshing: true }) {
					Text('123')
				}
					.commonStyle()
					.attributeModifier(this._blendModeRefreshModifier)
			}
			if (this.targetView == 'RelativeContainer') {
				RelativeContainer() {
					Row()
						.width(100)
						.height(100)
						.backgroundColor('#FF3333')
						.alignRules({
							top: { anchor: '__container__', align: VerticalAlign.Top },
							left: { anchor: '__container__', align: HorizontalAlign.Start }
						})
						.id('constraintSize')
				}
					.commonStyle()
					.attributeModifier(this._blendModeRelativeContainerModifier)
			}
			if (this.targetView == 'Row') {
				Row()
					.commonStyle()
					.attributeModifier(this._blendModeRowModifier)
			}
			if (this.targetView == 'RowSplit') {
				RowSplit() {
					Text('Text')
				}
					.commonStyle()
					.attributeModifier(this._blendModeRowSplitModifier)
			}
			if (this.targetView == 'Scroll') {
				Scroll() {
					Column() {
						ForEach([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], (item) => {
							Text('Scroll' + item.toString())
								.width('90%')
								.height(50)
								.backgroundColor(Color.White)
								.textAlign(TextAlign.Center)
						}, item => item)
					}
					.width('100%')
				}
					.scrollBar(BarState.On)
					.commonStyle()
					.attributeModifier(this._blendModeScrollModifier)
			}
			if (this.targetView == 'SideBarContainer') {
				SideBarContainer(SideBarContainerType.Embed) {
					Column() {
						ForEach([1, 2, 3], (item) => {
							Column({ space: 5 }) {
								Image($r('app.media.icon'))
									.width(50)
									.height(50)
								Text('Index0' + item)
									.fontSize(25)
							}
						})
					}
						.width('100%')
						.justifyContent(FlexAlign.SpaceEvenly)
						.backgroundColor(Color.Green)

					Column() {
						Text('SideBarContainer content')
							.fontSize(25)
					}
						.backgroundColor(Color.Orange)
				}
					.commonStyle()
					.attributeModifier(this._blendModeSideBarContainerModifier)
			}
			if (this.targetView == 'Stack') {
				Stack() {
				}
					.commonStyle()
					.attributeModifier(this._blendModeStackModifier)
			}
			if (this.targetView == 'Swiper') {
				Swiper() {
					ForEach([1, 2, 3], (item: string) => {
						Text('Swiper' + item)
							.width('90%')
							.height(50)
					}, item => item)
				}
					.indicator(true)
					.backgroundColor(Color.White)
					.commonStyle()
					.attributeModifier(this._blendModeSwiperModifier)
			}
			if (this.targetView == 'Tabs') {
				Tabs() {
					TabContent() {
						Column()
							.width('100%')
							.height('100%')
							.backgroundColor('#00CB87')
					}
				}
					.commonStyle()
					.attributeModifier(this._blendModeTabsModifier)
			}
			if (this.targetView == 'TabContent') {
				Tabs() {
					TabContent() {
						Text('TabContent Test')
							.width('100%')
							.height('100%')
							.backgroundColor(Color.White)
					}
						.tabBar('Tabs1')
						.commonStyle()
						.attributeModifier(this._blendModeTabContentModifier)
				}
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'WaterFlow') {
				WaterFlow() {
					ForEach([1, 2, 3, 4, 5, 6, 7, 8, 9], (item: number) => {
						FlowItem() {
							Column() {
								Text('WaterFlow' + item)
									.fontSize(12)
									.height('16')
								Image($r('app.media.icon'))
									.width(50)
									.height(50)
									.objectFit(ImageFit.Fill)
							}
						}
					}, item => item)
				}
					.commonStyle()
					.attributeModifier(this._blendModeWaterFlowModifier)
			}
			if (this.targetView == 'GridCol') {
				GridRow({ columns: 1, direction: GridRowDirection.Row }) {
					GridCol() {
						Row()
							.width('100%')
							.height('20vp')
					}
						.backgroundColor(Color.Yellow)
						.commonStyle()
						.attributeModifier(this._blendModeGridColModifier)
				}
					.backgroundColor(Color.Pink)
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'GridItem') {
				Grid() {
					GridItem() {
						Text('4')
							.backgroundColor(0xFAEEE0)
							.width('100%')
							.height('100%')
							.textAlign(TextAlign.Center)
					}
						.rowStart(1)
						.rowEnd(4)
						.backgroundColor(Color.Yellow)
						.commonStyle()
						.attributeModifier(this._blendModeGridItemModifier)
				}
					.backgroundColor(Color.Pink)
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'FlowItem') {
				WaterFlow() {
					ForEach([1, 2, 3, 4, 5, 6, 7, 8, 9], (item: number) => {
						FlowItem() {
							Column() {
								Text('WaterFlow' + item)
									.fontSize(12)
									.height('16')
								Image($r('app.media.icon'))
									.width(50)
									.height(50)
									.objectFit(ImageFit.Fill)
							}
						}
						.backgroundColor(Color.Yellow)
						.commonStyle()
						.attributeModifier(this._blendModeFlowItemModifier)
					}, item => item)
				}
					.backgroundColor(Color.Pink)
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'MenuItem') {
				Row() {
					Menu() {
						MenuItem({ startIcon: $r('app.media.icon'), content: 'MenuItem' })
							.commonStyle()
							.attributeModifier(this._blendModeMenuItemModifier)
					}
						.backgroundColor(Color.Yellow)
						.width('100%')
						.height('100%')
				}
					.width('100%')
					.height('100%')
					.backgroundColor(Color.Green)
			}
			if (this.targetView == 'MenuItemGroup') {
				Row() {
					Menu() {
						MenuItemGroup({ header: 'MenuItemGroup' }) {
							MenuItem({ startIcon: $r('app.media.icon'), content: 'MenuItem' })
						}
							.commonStyle()
							.attributeModifier(this._blendModeMenuItemGroupModifier)
					}
						.backgroundColor(Color.Yellow)
						.width('100%')
						.height('100%')
				}
					.width('100%')
					.height('100%')
					.backgroundColor(Color.Green)
			}
			if (this.targetView == 'CalendarPicker') {
				CalendarPicker({ hintRadius: 10, selected: new Date() })
					.commonStyle()
					.attributeModifier(this._blendModeCalendarPickerModifier)
			}
			if (this.targetView == 'Canvas') {
				Canvas(new CanvasRenderingContext2D(new RenderingContextSettings(true)))
					.backgroundColor('#FFFF00')
					.commonStyle()
					.attributeModifier(this._blendModeCanvasModifier)
			}
			if (this.targetView == 'FormLink') {
				FormLink({
					action: "router",
					abilityName: "EntryAbility",
					params: { 'message': 'testForRouter' }
				}) {
					Button("router event").width(120)
				}
					.commonStyle()
					.attributeModifier(this._blendModeFormLinkModifier)
			}
			if (this.targetView == 'Hyperlink') {
				Hyperlink('https://example.com/', 'Go to the developer website') {
				}
					.commonStyle()
					.attributeModifier(this._blendModeHyperlinkModifier)
			}
			if (this.targetView == 'Span') {
				Text() {
					Span('Span1')
						.commonStyle()
						.attributeModifier(this._blendModeSpanModifier)
				}
			}
		}
		.width(this.parentWidth)
		.height(this.parentHeight)
		.backgroundColor(this.parentBackGroundColor || '#FFFF00')
		.key(this.parentComponentKey)
	}
}
