//枚举类
const DATA_STATE_UNKNOWN = -1
const DATA_STATE_DISCONNECTED = 0
const DATA_STATE_CONNECTING = 1
const DATA_STATE_CONNECTED = 2
const DATA_STATE_SUSPENDED = 3

export const stateCommon ={
  DATA_STATE_UNKNOWN,
  DATA_STATE_DISCONNECTED,
  DATA_STATE_CONNECTING,
  DATA_STATE_CONNECTED,
  DATA_STATE_SUSPENDED
}