cat ../deqpgles2/build0001/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0001/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0002/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0002/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0003/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0003/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0004/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0004/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0005/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0005/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0006/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0006/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0007/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0007/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0008/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0008/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0009/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0009/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0010/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0010/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0011/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0011/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0012/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0012/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0013/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0013/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0014/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0014/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0015/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0015/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0016/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0016/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles2/build0017/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles2/build0017/BUILD.gn;rm FORMAT_RESULT.gn



cat ../deqpgles3/build0001/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0001/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0002/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0002/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0003/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0003/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0004/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0004/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0005/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0005/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0006/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0006/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0007/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0007/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0008/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0008/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0009/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0009/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0010/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0010/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0011/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0011/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0012/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0012/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0013/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0013/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0014/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0014/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0015/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0015/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0016/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0016/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0017/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0017/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0018/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0018/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0019/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0019/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0020/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0020/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0021/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0021/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0022/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0022/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0023/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0023/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0024/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0024/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0025/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0025/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0026/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0026/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0027/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0027/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0028/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0028/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0029/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0029/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0030/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0030/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0031/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0031/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0032/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0032/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0033/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0033/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0034/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0034/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0035/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0035/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0036/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0036/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0037/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0037/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0038/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0038/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0039/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0039/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0040/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0040/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0041/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0041/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0042/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0042/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0043/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0043/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0044/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0044/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles3/build0045/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles3/build0045/BUILD.gn;rm FORMAT_RESULT.gn

cat ../deqpgles31/build0001/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0001/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0002/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0002/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0003/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0003/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0004/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0004/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0005/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0005/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0006/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0006/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0007/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0007/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0008/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0008/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0009/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0009/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0010/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0010/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0011/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0011/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0012/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0012/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0013/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0013/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0014/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0014/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0015/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0015/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0016/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0016/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0017/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0017/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0018/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0018/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0019/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0019/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0020/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0020/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0021/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0021/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0022/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0022/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0023/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0023/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0024/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0024/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0025/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0025/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0026/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0026/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0027/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0027/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0028/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0028/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0029/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0029/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0030/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0030/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0031/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0031/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0032/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0032/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0033/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0033/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0034/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0034/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0035/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0035/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0036/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0036/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0037/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0037/BUILD.gn;rm FORMAT_RESULT.gn
cat ../deqpgles31/build0038/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../deqpgles31/build0038/BUILD.gn;rm FORMAT_RESULT.gn

cat ../khrgles2/build0001/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../khrgles2/build0001/BUILD.gn;rm FORMAT_RESULT.gn

cat ../khrgles3/build0001/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../khrgles3/build0001/BUILD.gn;rm FORMAT_RESULT.gn
cat ../khrgles3/build0002/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../khrgles3/build0002/BUILD.gn;rm FORMAT_RESULT.gn
cat ../khrgles3/build0003/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../khrgles3/build0003/BUILD.gn;rm FORMAT_RESULT.gn
cat ../khrgles3/build0004/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../khrgles3/build0004/BUILD.gn;rm FORMAT_RESULT.gn
cat ../khrgles3/build0005/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../khrgles3/build0005/BUILD.gn;rm FORMAT_RESULT.gn

cat ../khrgles31/build0001/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../khrgles31/build0001/BUILD.gn;rm FORMAT_RESULT.gn
cat ../khrgles31/build0002/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../khrgles31/build0002/BUILD.gn;rm FORMAT_RESULT.gn
cat ../khrgles31/build0003/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../khrgles31/build0003/BUILD.gn;rm FORMAT_RESULT.gn
cat ../khrgles31/build0004/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../khrgles31/build0004/BUILD.gn;rm FORMAT_RESULT.gn


cat ../khrgles32/build0001/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../khrgles32/build0001/BUILD.gn;rm FORMAT_RESULT.gn
cat ../khrgles32/build0002/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../khrgles32/build0002/BUILD.gn;rm FORMAT_RESULT.gn

cat ../khrglesext/build0001/BUILD.gn | ~/workspace/oh31/prebuilts/build-tools/linux-x86/bin/gn format --stdin > FORMAT_RESULT.gn;cp -f FORMAT_RESULT.gn ../khrglesext/build0001/BUILD.gn;rm FORMAT_RESULT.gn