//ts-nocheck
//public invalid
export const GENERAL_RUN_TIMES = 1000;
export const SAMPLING_RATE_44100 = 44100;
export const SAMPLING_RATE_48000 = 48000;
export const OUTPUT_NUMBER_0 = 0;
export const OUTPUT_NUMBER_1 = 1;

//--------------------------------------------------------------
export const INVALID_INPUT_PARAMETER_401 = 401;
export const INVALID_INPUT_PARAMETER_6800101 = 6800101;
export const UNSUPORTED_OPTION_6800104 = 6800104;
