/*
 * Copyright (C) 2024 Huawei Technologies Co., Ltd.
 * Licensed under the Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *     http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR
 * PURPOSE.
 * See the Mulan PSL v2 for more details.
 */
#ifndef __TEST_TCF_CMDID_H__
#define __TEST_TCF_CMDID_H__

typedef enum {
    CMD_TEE_GET_PROPERTY_AS_STRING = 0,
    CMD_TEE_GET_PROPERTY_AS_BOOL,
    CMD_TEE_GET_PROPERTY_AS_U32,
    CMD_TEE_GET_PROPERTY_AS_U64,
    CMD_TEE_GET_PROPERTY_AS_BINARY_BLOCK,
    CMD_TEE_GET_PROPERTY_AS_UUID,
    CMD_TEE_GET_PROPERTY_AS_IDENTITY,
    CMD_TEE_ALLOCATE_PROPERTY_ENUMERATOR,
    CMD_TEE_FREE_PROPERTY_ENUMERATOR,
    CMD_TEE_START_PROPERTY_ENUMERATOR,
    CMD_TEE_RESET_PROPERTY_ENUMERATOR,
    CMD_TEE_GET_PROPERTY_NAME_ENUMERATOR,
    CMD_TEE_GET_NEXT_PROPERTY_ENUMERATOR,
    CMD_TEE_MALLOC,
    CMD_TEE_FREE,
    CMD_TEE_REALLOC,
    CMD_TEE_MEM_MOVE,
    CMD_TEE_MEM_COMPARE,
    CMD_TEE_MEM_FILL,
    CMD_TEE_CHECK_MEMORY_ACCESS_RIGHTS,
    CMD_TEE_GET_INSTANCE_DATA,
    CMD_TEE_SET_INSTANCE_DATA,
    CMD_TEE_OPEN_TA_SESSION,
    CMD_TEE_INVOKE_TA_COMMAND,
    CMD_TEE_CLOSE_TA_SESSION,
    CMD_TEE_PANIC,
    CMD_TEST_PRINT,
    CMD_TEST_GETINFO,
    CMD_TEE_SHARE_MEM_API,
} TCFCmdId;

#define INPUT_ISNULL 1
#define OUTPUT_ISNULL 2
#define OUTPUTBUFFERSIZE_ISNULL 3
#define OUTPUTBUFFERSIZE_ISZERO 4
#define OUTPUTBUFFERSIZE_TOOSHORT 5
#define BUFFER_ISNOT_MALLOC 6
#define BUFFERSIZE_ISTOOBIG 7
#define BUFFER_IS_FREE 8
#define BUFFER_IS_PARAM 9
#define DESTANDSRC_ISSAME 10
#define DESTANDSRC_OVERLAP 11
#define BUFFER_IS_GLOBALVAR 12
#define BUFFER_IS_GLOBALCONSTVAR 13
#define RETURNORIGIN_ISNULL 14
#define TA_CRASH_FLAG 15
#define BUFFER_NOFILLNOSHARE 16
#endif