/*
 * Copyright (C) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// import getRootTest from "./getRoots.test.ets";
// import scanFileTest from "./scanFile.test.ets";
// import listFileTest from "./listFile.test.ets";
// import openFileTest from "./openFile.test.ets";
// import createFileTest from "./createFile.test.ets";
// import mkdirTest from "./mkdir.test.ets";
// import renameTest from "./rename.test.ets";
// import moveTest from "./move.test.ets";
// import deleteTest from "./delete.test.ets";
// import getFileInfoFromUriTest from "./getFileInfoFromUri.test.ets";
// import getFileInfoFromRelativePathTest from "./getFileInfoFromRelativePath.test.ets";
// import getThumbnailTest from "./getThumbnail.test.ets";
import copyTest from './copy.test.ets';

export default function mediaTestsuite(helper) {
    // getRootTest(helper);
    // scanFileTest(helper);
    // listFileTest(helper);
    // mkdirTest(helper);
    // createFileTest(helper);
    // moveTest(helper);
    // renameTest(helper);
    // openFileTest(helper);
    // getFileInfoFromUriTest(helper);
    // getFileInfoFromRelativePathTest(helper);
    // getThumbnailTest(helper);
    // deleteTest(helper);
    copyTest(helper);
}
