TT(RN,                        0x0p+0L,                        0x1p+0L,          0x0p+0, 0)
TT(RN,                       -0x0p+0L,                        0x1p+0L,          0x0p+0, 0)
TT(RN,                            inf,                            inf,          0x0p+0, 0)
TT(RN,                           -inf,                            inf,          0x0p+0, 0)
TT(RN,                            nan,                            nan,          0x0p+0, 0)
