TT(RN,                  0x0p+0,                  0x0p+0,          0x0p+0, 0)
TT(RN,                 -0x0p+0,                 -0x0p+0,          0x0p+0, 0)
TT(RN,                     inf,                     inf,          0x0p+0, 0)
TT(RN,                    -inf,                    -inf,          0x0p+0, 0)
TT(RN,                     NAN,                     NAN,          0x0p+0, 0)
