/*
 * Copyright (C) 2022 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import ActsAmsCallBackFifthScene from './util.test.js'
export default function testsuite() {
ActsAmsCallBackFifthScene()
ActsAmsCallBackFirstScene()
ActsAmsCallBackFourthScene()
ActsAmsCallBackSecondScene()
ActsAmsCallBackThirdScene()
ActsAmsTestFifthScene()
ActsAmsTestFirstScene()
ActsAmsTestFourthScene()
ActsAmsTestSecondScene()
ActsAmsTestThirdScene()
ActsStServiceAbilityTest()
ActsGetAbilityStateTest()
ActsDataAbilityHelperTest()
ActsStServiceAbilityTest()
ActsStServiceAbilityTest()
ActsDataUriUtilsTest()
ActsAbilityRunningInfosTest()
ActsContextTest()
ConfigurationTest()
CoverApiTest()
ActsFeatureAbilityTest()
ConnectAbilityTest()
ActsGetWantTest()
ActsAccountPressure()
ActsAccountAddAccount()
ActsAccountAppAccess()
ActsAccountAssociatedData()
ActsCreatAppAccountManager()
ActsAccountCredential()
ActsAccountDeleteAccount()
ActsAccountSetGetExtraInfo()
ActsAccountNoPermission()
ActsAccountOAuthToken()
ActsAccountChangeOnOff()
ActsGetAllAccounts()
ActsSetCheckSyncEnable()
ActsGetAllAccessibleAccounts()
ActsGetAllAccessibleMultiple()
ActsOsAccountThirdPartyTest_third_1()
ActsOsAccountThirdPartyTest_third_1()
AccountTest()
basicabilityapi()
aceJsTest()
mediaquery()
AccessibleCaptionConfiguration()
AccessibleCheckAbility()
AccessibleRegisterState()
AccessibleSendEvent()
ActsBmsAccessTokenTest()
ActsBmsGetBackGroundModes()
ActsBmsQueryAbilityByWant()
ActsBmsHapModuleTest()
ActsBmsHasInstalldTest()
ActsBmsJsTest()
ActsBmsJsUnPermissionTest()
ActsBmsMetaDataTest()
ActsBundleManagerTest()
ActsZlibTest()
bluetoothhostTest()
bluetoothhostTest()
bluetoothhostTest_host_1()
bluetoothhostTest_host_3()
bluetoothhostTest_host_2()
bluetoothhostTest()
ActsRpcClientJsTest()
ActsRpcJsTest()
ACTS_WifiTest()
ACTS_WifiTest()
WaitTest()
XmlTest()
ChildProcessTest()
UriTest()
UrlFunTest()
TextEncoderTest()
ScopeTest()
Base64Test()
RationalNumberFunTest()
LruBufferFunTest()
TypesTest()
}
