/*
 * Copyright (c) 2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import attrsManager from '../../common/AttrsManager'
import router from '@ohos.router'

class AlphabetIndexerModifier implements AttributeModifier<AlphabetIndexerAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: AlphabetIndexerAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class BadgeModifier implements AttributeModifier<BadgeAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: BadgeAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class ButtonModifier implements AttributeModifier<ButtonAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: ButtonAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class BlankModifier implements AttributeModifier<BlankAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: BlankAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class CalendarPickerModifier implements AttributeModifier<CalendarPickerAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: CalendarPickerAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class CanvasModifier implements AttributeModifier<CanvasAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: CanvasAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class CheckboxModifier implements AttributeModifier<CheckboxAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: CheckboxAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class CheckboxGroupModifier implements AttributeModifier<CheckboxGroupAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: CheckboxGroupAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class CircleModifier implements AttributeModifier<CircleAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: CircleAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class ColumnModifier implements AttributeModifier<ColumnAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: ColumnAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class ColumnSplitModifier implements AttributeModifier<ColumnSplitAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: ColumnSplitAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class CounterModifier implements AttributeModifier<CounterAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: CounterAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class DataPanelModifier implements AttributeModifier<DataPanelAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: DataPanelAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class DatePickerModifier implements AttributeModifier<DatePickerAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: DatePickerAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class DividerModifier implements AttributeModifier<DividerAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: DividerAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class EllipseModifier implements AttributeModifier<EllipseAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: EllipseAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class FlexModifier implements AttributeModifier<FlexAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: FlexAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class FlowItemModifier implements AttributeModifier<FlowItemAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: FlowItemAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class FormLinkModifier implements AttributeModifier<FormLinkAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: FormLinkAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class GaugeModifier implements AttributeModifier<GaugeAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: GaugeAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class GridModifier implements AttributeModifier<GridAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: GridAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class GridColModifier implements AttributeModifier<GridColAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: GridColAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class GridItemModifier implements AttributeModifier<GridItemAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: GridItemAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class GridRowModifier implements AttributeModifier<GridRowAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: GridRowAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class HyperlinkModifier implements AttributeModifier<HyperlinkAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: HyperlinkAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class ImageModifier implements AttributeModifier<ImageAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: ImageAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class ImageAnimatorModifier implements AttributeModifier<ImageAnimatorAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: ImageAnimatorAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class LineModifier implements AttributeModifier<LineAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: LineAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class ListModifier implements AttributeModifier<ListAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: ListAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class ListItemModifier implements AttributeModifier<ListItemAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: ListItemAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class ListItemGroupModifier implements AttributeModifier<ListItemGroupAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: ListItemGroupAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class LoadingProgressModifier implements AttributeModifier<LoadingProgressAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: LoadingProgressAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class MarqueeModifier implements AttributeModifier<MarqueeAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: MarqueeAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class MenuModifier implements AttributeModifier<MenuAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: MenuAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class MenuItemModifier implements AttributeModifier<MenuItemAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: MenuItemAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class MenuItemGroupModifier implements AttributeModifier<MenuItemGroupAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: MenuItemGroupAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class NavDestinationModifier implements AttributeModifier<NavDestinationAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: NavDestinationAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class NavigationModifier implements AttributeModifier<NavigationAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: NavigationAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class NavigatorModifier implements AttributeModifier<NavigatorAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: NavigatorAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class NavRouterModifier implements AttributeModifier<NavRouterAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: NavRouterAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class PanelModifier implements AttributeModifier<PanelAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: PanelAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class PathModifier implements AttributeModifier<PathAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: PathAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class PolygonModifier implements AttributeModifier<PolygonAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: PolygonAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class PolylineModifier implements AttributeModifier<PolylineAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: PolylineAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class ProgressModifier implements AttributeModifier<ProgressAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: ProgressAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class QRCodeModifier implements AttributeModifier<QRCodeAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: QRCodeAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class RadioModifier implements AttributeModifier<RadioAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: RadioAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class RatingModifier implements AttributeModifier<RatingAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: RatingAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class RectModifier implements AttributeModifier<RectAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: RectAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class RefreshModifier implements AttributeModifier<RefreshAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: RefreshAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class RelativeContainerModifier implements AttributeModifier<RelativeContainerAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: RelativeContainerAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class RemoteWindowModifier implements AttributeModifier<RemoteWindowAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: RemoteWindowAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class RichEditorModifier implements AttributeModifier<RichEditorAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: RichEditorAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class RichTextModifier implements AttributeModifier<RichTextAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: RichTextAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class RowModifier implements AttributeModifier<RowAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: RowAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class RowSplitModifier implements AttributeModifier<RowSplitAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: RowSplitAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class ScrollModifier implements AttributeModifier<ScrollAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: ScrollAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class ScrollBarModifier implements AttributeModifier<ScrollBarAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: ScrollBarAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class SearchModifier implements AttributeModifier<SearchAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: SearchAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class SelectModifier implements AttributeModifier<SelectAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: SelectAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class ShapeModifier implements AttributeModifier<ShapeAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: ShapeAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class SideBarContainerModifier implements AttributeModifier<SideBarContainerAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: SideBarContainerAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class SliderModifier implements AttributeModifier<SliderAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: SliderAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class SpanModifier implements AttributeModifier<SpanAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: SpanAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class StackModifier implements AttributeModifier<StackAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: StackAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class StepperModifier implements AttributeModifier<StepperAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: StepperAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class StepperItemModifier implements AttributeModifier<StepperItemAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: StepperItemAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class SwiperModifier implements AttributeModifier<SwiperAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: SwiperAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class TabContentModifier implements AttributeModifier<TabContentAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: TabContentAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class TabsModifier implements AttributeModifier<TabsAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: TabsAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class TextModifier implements AttributeModifier<TextAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: TextAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class TextAreaModifier implements AttributeModifier<TextAreaAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: TextAreaAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class TextClockModifier implements AttributeModifier<TextClockAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: TextClockAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class TextInputModifier implements AttributeModifier<TextInputAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: TextInputAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class TextPickerModifier implements AttributeModifier<TextPickerAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: TextPickerAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class TextTimerModifier implements AttributeModifier<TextTimerAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: TextTimerAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class TimePickerModifier implements AttributeModifier<TimePickerAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: TimePickerAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class ToggleModifier implements AttributeModifier<ToggleAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: ToggleAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class VideoModifier implements AttributeModifier<VideoAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: VideoAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class WaterFlowModifier implements AttributeModifier<WaterFlowAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: WaterFlowAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class WebModifier implements AttributeModifier<WebAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: WebAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class WindowSceneModifier implements AttributeModifier<WindowSceneAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: WindowSceneAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

class XComponentModifier implements AttributeModifier<XComponentAttribute> {
	mDragPreviewOptions: DragPreviewOptions = { mode: DragPreviewMode.AUTO }

	applyNormalAttribute(instance: XComponentAttribute): void {
		instance.dragPreviewOptions(this.mDragPreviewOptions)
	}
}

@Entry
@Component
struct DragPreviewOptionsPage {
	@State _dragPreviewOptionsAlphabetIndexerModifier: AlphabetIndexerModifier = new AlphabetIndexerModifier()
	@State _dragPreviewOptionsBadgeModifier: BadgeModifier = new BadgeModifier()
	@State _dragPreviewOptionsButtonModifier: ButtonModifier = new ButtonModifier()
	@State _dragPreviewOptionsBlankModifier: BlankModifier = new BlankModifier()
	@State _dragPreviewOptionsCalendarPickerModifier: CalendarPickerModifier = new CalendarPickerModifier()
	@State _dragPreviewOptionsCanvasModifier: CanvasModifier = new CanvasModifier()
	@State _dragPreviewOptionsCheckboxModifier: CheckboxModifier = new CheckboxModifier()
	@State _dragPreviewOptionsCheckboxGroupModifier: CheckboxGroupModifier = new CheckboxGroupModifier()
	@State _dragPreviewOptionsCircleModifier: CircleModifier = new CircleModifier()
	@State _dragPreviewOptionsColumnModifier: ColumnModifier = new ColumnModifier()
	@State _dragPreviewOptionsColumnSplitModifier: ColumnSplitModifier = new ColumnSplitModifier()
	@State _dragPreviewOptionsCounterModifier: CounterModifier = new CounterModifier()
	@State _dragPreviewOptionsDataPanelModifier: DataPanelModifier = new DataPanelModifier()
	@State _dragPreviewOptionsDatePickerModifier: DatePickerModifier = new DatePickerModifier()
	@State _dragPreviewOptionsDividerModifier: DividerModifier = new DividerModifier()
	@State _dragPreviewOptionsEllipseModifier: EllipseModifier = new EllipseModifier()
	@State _dragPreviewOptionsFlexModifier: FlexModifier = new FlexModifier()
	@State _dragPreviewOptionsFlowItemModifier: FlowItemModifier = new FlowItemModifier()
	@State _dragPreviewOptionsFormLinkModifier: FormLinkModifier = new FormLinkModifier()
	@State _dragPreviewOptionsGaugeModifier: GaugeModifier = new GaugeModifier()
	@State _dragPreviewOptionsGridModifier: GridModifier = new GridModifier()
	@State _dragPreviewOptionsGridColModifier: GridColModifier = new GridColModifier()
	@State _dragPreviewOptionsGridItemModifier: GridItemModifier = new GridItemModifier()
	@State _dragPreviewOptionsGridRowModifier: GridRowModifier = new GridRowModifier()
	@State _dragPreviewOptionsHyperlinkModifier: HyperlinkModifier = new HyperlinkModifier()
	@State _dragPreviewOptionsImageModifier: ImageModifier = new ImageModifier()
	@State _dragPreviewOptionsImageAnimatorModifier: ImageAnimatorModifier = new ImageAnimatorModifier()
	@State _dragPreviewOptionsLineModifier: LineModifier = new LineModifier()
	@State _dragPreviewOptionsListModifier: ListModifier = new ListModifier()
	@State _dragPreviewOptionsListItemModifier: ListItemModifier = new ListItemModifier()
	@State _dragPreviewOptionsListItemGroupModifier: ListItemGroupModifier = new ListItemGroupModifier()
	@State _dragPreviewOptionsLoadingProgressModifier: LoadingProgressModifier = new LoadingProgressModifier()
	@State _dragPreviewOptionsMarqueeModifier: MarqueeModifier = new MarqueeModifier()
	@State _dragPreviewOptionsMenuModifier: MenuModifier = new MenuModifier()
	@State _dragPreviewOptionsMenuItemModifier: MenuItemModifier = new MenuItemModifier()
	@State _dragPreviewOptionsMenuItemGroupModifier: MenuItemGroupModifier = new MenuItemGroupModifier()
	@State _dragPreviewOptionsNavDestinationModifier: NavDestinationModifier = new NavDestinationModifier()
	@State _dragPreviewOptionsNavigationModifier: NavigationModifier = new NavigationModifier()
	@State _dragPreviewOptionsNavigatorModifier: NavigatorModifier = new NavigatorModifier()
	@State _dragPreviewOptionsNavRouterModifier: NavRouterModifier = new NavRouterModifier()
	@State _dragPreviewOptionsPanelModifier: PanelModifier = new PanelModifier()
	@State _dragPreviewOptionsPathModifier: PathModifier = new PathModifier()
	@State _dragPreviewOptionsPolygonModifier: PolygonModifier = new PolygonModifier()
	@State _dragPreviewOptionsPolylineModifier: PolylineModifier = new PolylineModifier()
	@State _dragPreviewOptionsProgressModifier: ProgressModifier = new ProgressModifier()
	@State _dragPreviewOptionsQRCodeModifier: QRCodeModifier = new QRCodeModifier()
	@State _dragPreviewOptionsRadioModifier: RadioModifier = new RadioModifier()
	@State _dragPreviewOptionsRatingModifier: RatingModifier = new RatingModifier()
	@State _dragPreviewOptionsRectModifier: RectModifier = new RectModifier()
	@State _dragPreviewOptionsRefreshModifier: RefreshModifier = new RefreshModifier()
	@State _dragPreviewOptionsRelativeContainerModifier: RelativeContainerModifier = new RelativeContainerModifier()
	@State _dragPreviewOptionsRemoteWindowModifier: RemoteWindowModifier = new RemoteWindowModifier()
	@State _dragPreviewOptionsRichEditorModifier: RichEditorModifier = new RichEditorModifier()
	@State _dragPreviewOptionsRichTextModifier: RichTextModifier = new RichTextModifier()
	@State _dragPreviewOptionsRowModifier: RowModifier = new RowModifier()
	@State _dragPreviewOptionsRowSplitModifier: RowSplitModifier = new RowSplitModifier()
	@State _dragPreviewOptionsScrollModifier: ScrollModifier = new ScrollModifier()
	@State _dragPreviewOptionsScrollBarModifier: ScrollBarModifier = new ScrollBarModifier()
	@State _dragPreviewOptionsSearchModifier: SearchModifier = new SearchModifier()
	@State _dragPreviewOptionsSelectModifier: SelectModifier = new SelectModifier()
	@State _dragPreviewOptionsShapeModifier: ShapeModifier = new ShapeModifier()
	@State _dragPreviewOptionsSideBarContainerModifier: SideBarContainerModifier = new SideBarContainerModifier()
	@State _dragPreviewOptionsSliderModifier: SliderModifier = new SliderModifier()
	@State _dragPreviewOptionsSpanModifier: SpanModifier = new SpanModifier()
	@State _dragPreviewOptionsStackModifier: StackModifier = new StackModifier()
	@State _dragPreviewOptionsStepperModifier: StepperModifier = new StepperModifier()
	@State _dragPreviewOptionsStepperItemModifier: StepperItemModifier = new StepperItemModifier()
	@State _dragPreviewOptionsSwiperModifier: SwiperModifier = new SwiperModifier()
	@State _dragPreviewOptionsTabContentModifier: TabContentModifier = new TabContentModifier()
	@State _dragPreviewOptionsTabsModifier: TabsModifier = new TabsModifier()
	@State _dragPreviewOptionsTextModifier: TextModifier = new TextModifier()
	@State _dragPreviewOptionsTextAreaModifier: TextAreaModifier = new TextAreaModifier()
	@State _dragPreviewOptionsTextClockModifier: TextClockModifier = new TextClockModifier()
	@State _dragPreviewOptionsTextInputModifier: TextInputModifier = new TextInputModifier()
	@State _dragPreviewOptionsTextPickerModifier: TextPickerModifier = new TextPickerModifier()
	@State _dragPreviewOptionsTextTimerModifier: TextTimerModifier = new TextTimerModifier()
	@State _dragPreviewOptionsTimePickerModifier: TimePickerModifier = new TimePickerModifier()
	@State _dragPreviewOptionsToggleModifier: ToggleModifier = new ToggleModifier()
	@State _dragPreviewOptionsVideoModifier: VideoModifier = new VideoModifier()
	@State _dragPreviewOptionsWaterFlowModifier: WaterFlowModifier = new WaterFlowModifier()
	@State _dragPreviewOptionsWebModifier: WebModifier = new WebModifier()
	@State _dragPreviewOptionsWindowSceneModifier: WindowSceneModifier = new WindowSceneModifier()
	@State _dragPreviewOptionsXComponentModifier: XComponentModifier = new XComponentModifier()
	@State targetView: string = router.getParams() ? router.getParams()['view']['targetView'] : ''
	@State componentKey: string = router.getParams() ? router.getParams()['view']['componentKey'] : ''
	@State parentWidth: number = router.getParams() ? router.getParams()['view']['parentWidth'] : 0
	@State parentHeight: number = router.getParams() ? router.getParams()['view']['parentHeight'] : 0
	@State columns: number = router.getParams() ? router.getParams()['view']['columns'] : 0
	@State gutter: number = router.getParams() ? router.getParams()['view']['gutter'] : 0
	@State parentBackGroundColor: string = router.getParams() ? router.getParams()['view']['parentBackGroundColor'] : '#FFFF00'
	@State parentComponentKey: string = router.getParams() ? router.getParams()['view']['parentComponentKey'] : ''

	onPageShow() {
		console.info('dragPreviewOptions translate page show called ')
		attrsManager.registerDataChange(value => {
			console.info('dragPreviewOptions [registerDataChange] ' + JSON.stringify(value.dragPreviewOptions))
			this._dragPreviewOptionsAlphabetIndexerModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsBadgeModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsButtonModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsBlankModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsCalendarPickerModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsCanvasModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsCheckboxModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsCheckboxGroupModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsCircleModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsColumnModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsColumnSplitModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsCounterModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsDataPanelModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsDatePickerModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsDividerModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsEllipseModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsFlexModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsFlowItemModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsFormLinkModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsGaugeModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsGridModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsGridColModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsGridItemModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsGridRowModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsHyperlinkModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsImageModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsImageAnimatorModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsLineModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsListModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsListItemModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsListItemGroupModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsLoadingProgressModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsMarqueeModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsMenuModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsMenuItemModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsMenuItemGroupModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsNavDestinationModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsNavigationModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsNavigatorModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsNavRouterModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsPanelModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsPathModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsPolygonModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsPolylineModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsProgressModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsQRCodeModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsRadioModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsRatingModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsRectModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsRefreshModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsRelativeContainerModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsRemoteWindowModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsRichEditorModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsRichTextModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsRowModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsRowSplitModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsScrollModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsScrollBarModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsSearchModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsSelectModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsShapeModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsSideBarContainerModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsSliderModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsSpanModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsStackModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsStepperModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsStepperItemModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsSwiperModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsTabContentModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsTabsModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsTextModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsTextAreaModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsTextClockModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsTextInputModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsTextPickerModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsTextTimerModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsTimePickerModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsToggleModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsVideoModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsWaterFlowModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsWebModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsWindowSceneModifier.mDragPreviewOptions = value.dragPreviewOptions
			this._dragPreviewOptionsXComponentModifier.mDragPreviewOptions = value.dragPreviewOptions
		})
	}

	@Styles
  commonStyle() {
		.key(this.componentKey)
  }

	build() {
		Column() {
			if (this.targetView == 'AlphabetIndexer') {
				AlphabetIndexer({ arrayValue: ['#', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], selected: 0 })
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsAlphabetIndexerModifier)
			}
			if (this.targetView == 'Button') {
				Button('button1')
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsButtonModifier)
			}
			if (this.targetView == 'Blank') {
				Blank()
					.backgroundColor(Color.Yellow)
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsBlankModifier)
			}
			if (this.targetView == 'Checkbox') {
				Checkbox()
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsCheckboxModifier)
			}
			if (this.targetView == 'CheckboxGroup') {
				CheckboxGroup({ group: 'checkboxGroup' })
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsCheckboxGroupModifier)
			}
			if (this.targetView == 'DataPanel') {
				DataPanel({ values: [5, 10, 10, 7, 9, 10, 10, 10, 10] })
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsDataPanelModifier)
			}
			if (this.targetView == 'DatePicker') {
				DatePicker({ start: new Date('1970-1-1'), end: new Date('2100-1-1') })
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsDatePickerModifier)
			}
			if (this.targetView == 'Divider') {
				Divider()
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsDividerModifier)
			}
			if (this.targetView == 'Gauge') {
				Gauge({ value: 105 })
					.colors([[0x317AF7, 1], [0x5BA854, 1], [0xE08C3A, 1], [0x9C554B, 1]])
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsGaugeModifier)
			}
			if (this.targetView == 'Image') {
				Image($r('app.media.icon'))
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsImageModifier)
			}
			if (this.targetView == 'ImageAnimator') {
				ImageAnimator()
					.images([{ src: $r('app.media.icon') }])
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsImageAnimatorModifier)
			}
			if (this.targetView == 'LoadingProgress') {
				LoadingProgress()
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsLoadingProgressModifier)
			}
			if (this.targetView == 'Marquee') {
				Marquee({ 
					start: true,
					step: 50,
					loop: Infinity,
					fromStart: true,
					src: 'Running Marquee starts rolling'
				})
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsMarqueeModifier)
			}
			if (this.targetView == 'Navigation') {
				Navigation() {
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsNavigationModifier)
			}
			if (this.targetView == 'Menu') {
				Menu() {
					MenuItem({ startIcon: $r('app.media.icon'), content: 'Menu' })
				}
					.backgroundColor(Color.Yellow)
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsMenuModifier)
			}
			if (this.targetView == 'NavRouter') {
				NavRouter() {
					Row() {
						Image($r('app.media.icon'))
					}

					NavDestination() {
						Text('NavDestination')
							.fontSize(10)
					}
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsNavRouterModifier)
			}
			if (this.targetView == 'Progress') {
				Progress({ value: 10, type: ProgressType.Eclipse })
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsProgressModifier)
			}
			if (this.targetView == 'QRCode') {
				QRCode('Running Marquee starts rolling')
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsQRCodeModifier)
			}
			if (this.targetView == 'Radio') {
				Radio({ value: 'Radio1', group: 'radioGroup' })
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsRadioModifier)
			}
			if (this.targetView == 'Rating') {
				Rating({ rating: 3.5, indicator: false })
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsRatingModifier)
			}
			if (this.targetView == 'ScrollBar') {
				ScrollBar({ scroller: new Scroller(), state: BarState.On }) {
					Text()
						.width(20)
						.height(100)
						.borderRadius(10)
						.backgroundColor('#C0C0C0')
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsScrollBarModifier)
			}
			if (this.targetView == 'Search') {
				Search()
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsSearchModifier)
			}
			if (this.targetView == 'Select') {
				Select([{ value: 'aaa' }, { value: 'bbb' }])
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsSelectModifier)
			}
			if (this.targetView == 'Slider') {
				Slider({ value: 50, min: 0, max: 100, style: SliderStyle.OutSet })
					.showTips(true)
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsSliderModifier)
			}
			if (this.targetView == 'Stepper') {
				Stepper() {
					StepperItem() {
						Column() {
							Text('Page One')
						}
					}
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsStepperModifier)
			}
			if (this.targetView == 'StepperItem') {
				Stepper() {
					StepperItem() {
						Column() {
							Text('Page One')
						}
					}
						.backgroundColor(Color.Red)
						.commonStyle()
						.attributeModifier(this._dragPreviewOptionsStepperItemModifier)
				}
					.backgroundColor(Color.Yellow)
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'Text') {
				Text('text1')
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsTextModifier)
			}
			if (this.targetView == 'TextArea') {
				TextArea({ placeholder: 'The text area can hold an unlimited amount of text. input your word...' })
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsTextAreaModifier)
			}
			if (this.targetView == 'TextClock') {
				TextClock({ timeZoneOffset: -8 })
					.format('hms')
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsTextClockModifier)
			}
			if (this.targetView == 'TextInput') {
				TextInput({ placeholder: 'input your word...' })
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsTextInputModifier)
			}
			if (this.targetView == 'TextPicker') {
				TextPicker({ range: ['#', 'A', 'B', 'C', 'D', 'E', 'F', 'G'] })
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsTextPickerModifier)
			}
			if (this.targetView == 'TextTimer') {
				TextTimer({ isCountDown: true, count: 30000 })
					.format('mm:ss.SS')
					.fontColor(Color.Black)
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsTextTimerModifier)
			}
			if (this.targetView == 'TimePicker') {
				TimePicker({ selected: new Date('2022-07-22T08:00:00') })
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsTimePickerModifier)
			}
			if (this.targetView == 'Toggle') {
				Toggle({ type: ToggleType.Switch, isOn: false })
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsToggleModifier)
			}
			if (this.targetView == 'Web') {
				Web({ src: 'www.example.com', controller: new WebController() })
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsWebModifier)
			}
			if (this.targetView == 'Circle') {
				Circle()
					.width(150)
					.height(200)
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsCircleModifier)
			}
			if (this.targetView == 'Ellipse') {
				Ellipse()
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsEllipseModifier)
			}
			if (this.targetView == 'Line') {
				Line()
					.startPoint([0, 0])
					.endPoint([50, 100])
					.backgroundColor(Color.Black)
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsLineModifier)
			}
			if (this.targetView == 'Polyline') {
				Polyline()
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsPolylineModifier)
			}
			if (this.targetView == 'Polygon') {
				Polygon()
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsPolygonModifier)
			}
			if (this.targetView == 'Path') {
				Path()
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsPathModifier)
			}
			if (this.targetView == 'Rect') {
				Rect()
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsRectModifier)
			}
			if (this.targetView == 'Shape') {
				Shape() {
					Rect()
						.width(100)
						.height(50)
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsShapeModifier)
			}
			if (this.targetView == 'Badge') {
				Badge({ count: 50, style: { color: 0xFFFFFF, fontSize: 16, badgeSize: 20, badgeColor: Color.Red } }) {
					Button('message')
						.width(100)
						.height(50)
						.backgroundColor(0x317aff)
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsBadgeModifier)
			}
			if (this.targetView == 'Column') {
				Column() {
					Button()
						.width(100)
						.height(50)
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsColumnModifier)
			}
			if (this.targetView == 'ColumnSplit') {
				ColumnSplit() {
					Text('1')
						.width('100%')
						.height(50)
						.backgroundColor(0xF5DEB3)
						.textAlign(TextAlign.Center)
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsColumnSplitModifier)
			}
			if (this.targetView == 'Counter') {
				Counter() {
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsCounterModifier)
			}
			if (this.targetView == 'Flex') {
				Flex() {
					Text('1')
						.width('20%')
						.height(50)
						.backgroundColor(0xF5DEB3)
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsFlexModifier)
			}
			if (this.targetView == 'GridRow') {
				GridRow({ columns: 1, direction: GridRowDirection.Row }) {
					ForEach(
						[Color.Red, Color.Orange, Color.Yellow, Color.Green, Color.Pink, Color.Grey, Color.Blue, Color.Brown],
						(color) => {
							GridCol({ span: { xs: 1, sm: 2, md: 3, lg: 4 } }) {
								Row()
									.width('100%')
									.height('20vp')
							}
								.borderColor(color)
								.borderWidth(2)
						}
					)
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsGridRowModifier)
			}
			if (this.targetView == 'Grid') {
				Grid() {
					ForEach(['0', '1', '2', '3', '4'], () => {
						ForEach(['0', '1', '2', '3', '4'], (day: string) => {
							GridItem() {
								Text(day)
									.backgroundColor(Color.White)
									.width('100%')
									.height('100%')
									.textAlign(TextAlign.Center)
							}
						})
					})
				}
					.columnsTemplate('1fr 1fr 1fr 1fr 1fr')
					.rowsTemplate('1fr 1fr 1fr 1fr 1fr')
					.backgroundColor(0xFAEEE0)
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsGridModifier)
			}
			if (this.targetView == 'List') {
				List() {
				}
					.height('100%')
					.width('100%')
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsListModifier)
			}
			if (this.targetView == 'ListItem') {
				List({ space: 20, initialIndex: 0 }) {
					ListItem() {
						Text('item1')
							.width('100%')
							.textAlign(TextAlign.Center)
							.backgroundColor(Color.White)
					}
						.commonStyle()
						.attributeModifier(this._dragPreviewOptionsListItemModifier)
				}
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'ListItemGroup') {
				List({ space: 0, initialIndex: 0 }) {
					ListItemGroup()
						.backgroundColor(Color.Yellow)
						.commonStyle()
						.attributeModifier(this._dragPreviewOptionsListItemGroupModifier)
				}
					.backgroundColor(Color.Pink)
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'Navigator') {
				Navigator() {
					Text('Go to back page')
						.width('100%')
						.height(20)
				}
					.backgroundColor(Color.Red)
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsNavigatorModifier)
			}
			if (this.targetView == 'Panel') {
				Panel(true) {
					Text('Text')
				}
					.backgroundColor(Color.Yellow)
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsPanelModifier)
			}
			if (this.targetView == 'Refresh') {
				Refresh({ refreshing: true }) {
					Text('123')
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsRefreshModifier)
			}
			if (this.targetView == 'RelativeContainer') {
				RelativeContainer() {
					Row()
						.width(100)
						.height(100)
						.backgroundColor('#FF3333')
						.alignRules({
							top: { anchor: '__container__', align: VerticalAlign.Top },
							left: { anchor: '__container__', align: HorizontalAlign.Start }
						})
						.id('constraintSize')
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsRelativeContainerModifier)
			}
			if (this.targetView == 'Row') {
				Row()
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsRowModifier)
			}
			if (this.targetView == 'RowSplit') {
				RowSplit() {
					Text('Text')
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsRowSplitModifier)
			}
			if (this.targetView == 'Scroll') {
				Scroll() {
					Column() {
						ForEach([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], (item) => {
							Text('Scroll' + item.toString())
								.width('90%')
								.height(50)
								.backgroundColor(Color.White)
								.textAlign(TextAlign.Center)
						}, item => item)
					}
					.width('100%')
				}
					.scrollBar(BarState.On)
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsScrollModifier)
			}
			if (this.targetView == 'SideBarContainer') {
				SideBarContainer(SideBarContainerType.Embed) {
					Column() {
						ForEach([1, 2, 3], (item) => {
							Column({ space: 5 }) {
								Image($r('app.media.icon'))
									.width(50)
									.height(50)
								Text('Index0' + item)
									.fontSize(25)
							}
						})
					}
						.width('100%')
						.justifyContent(FlexAlign.SpaceEvenly)
						.backgroundColor(Color.Green)

					Column() {
						Text('SideBarContainer content')
							.fontSize(25)
					}
						.backgroundColor(Color.Orange)
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsSideBarContainerModifier)
			}
			if (this.targetView == 'Stack') {
				Stack() {
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsStackModifier)
			}
			if (this.targetView == 'Swiper') {
				Swiper() {
					ForEach([1, 2, 3], (item: string) => {
						Text('Swiper' + item)
							.width('90%')
							.height(50)
					}, item => item)
				}
					.indicator(true)
					.backgroundColor(Color.White)
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsSwiperModifier)
			}
			if (this.targetView == 'Tabs') {
				Tabs() {
					TabContent() {
						Column()
							.width('100%')
							.height('100%')
							.backgroundColor('#00CB87')
					}
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsTabsModifier)
			}
			if (this.targetView == 'TabContent') {
				Tabs() {
					TabContent() {
						Text('TabContent Test')
							.width('100%')
							.height('100%')
							.backgroundColor(Color.White)
					}
						.tabBar('Tabs1')
						.commonStyle()
						.attributeModifier(this._dragPreviewOptionsTabContentModifier)
				}
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'WaterFlow') {
				WaterFlow() {
					ForEach([1, 2, 3, 4, 5, 6, 7, 8, 9], (item: number) => {
						FlowItem() {
							Column() {
								Text('WaterFlow' + item)
									.fontSize(12)
									.height('16')
								Image($r('app.media.icon'))
									.width(50)
									.height(50)
									.objectFit(ImageFit.Fill)
							}
						}
					}, item => item)
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsWaterFlowModifier)
			}
			if (this.targetView == 'GridCol') {
				GridRow({ columns: 1, direction: GridRowDirection.Row }) {
					GridCol() {
						Row()
							.width('100%')
							.height('20vp')
					}
						.backgroundColor(Color.Yellow)
						.commonStyle()
						.attributeModifier(this._dragPreviewOptionsGridColModifier)
				}
					.backgroundColor(Color.Pink)
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'GridItem') {
				Grid() {
					GridItem() {
						Text('4')
							.backgroundColor(0xFAEEE0)
							.width('100%')
							.height('100%')
							.textAlign(TextAlign.Center)
					}
						.rowStart(1)
						.rowEnd(4)
						.backgroundColor(Color.Yellow)
						.commonStyle()
						.attributeModifier(this._dragPreviewOptionsGridItemModifier)
				}
					.backgroundColor(Color.Pink)
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'FlowItem') {
				WaterFlow() {
					ForEach([1, 2, 3, 4, 5, 6, 7, 8, 9], (item: number) => {
						FlowItem() {
							Column() {
								Text('WaterFlow' + item)
									.fontSize(12)
									.height('16')
								Image($r('app.media.icon'))
									.width(50)
									.height(50)
									.objectFit(ImageFit.Fill)
							}
						}
						.backgroundColor(Color.Yellow)
						.commonStyle()
						.attributeModifier(this._dragPreviewOptionsFlowItemModifier)
					}, item => item)
				}
					.backgroundColor(Color.Pink)
					.width('100%')
					.height('100%')
			}
			if (this.targetView == 'MenuItem') {
				Row() {
					Menu() {
						MenuItem({ startIcon: $r('app.media.icon'), content: 'MenuItem' })
							.commonStyle()
							.attributeModifier(this._dragPreviewOptionsMenuItemModifier)
					}
						.backgroundColor(Color.Yellow)
						.width('100%')
						.height('100%')
				}
					.width('100%')
					.height('100%')
					.backgroundColor(Color.Green)
			}
			if (this.targetView == 'MenuItemGroup') {
				Row() {
					Menu() {
						MenuItemGroup({ header: 'MenuItemGroup' }) {
							MenuItem({ startIcon: $r('app.media.icon'), content: 'MenuItem' })
						}
							.commonStyle()
							.attributeModifier(this._dragPreviewOptionsMenuItemGroupModifier)
					}
						.backgroundColor(Color.Yellow)
						.width('100%')
						.height('100%')
				}
					.width('100%')
					.height('100%')
					.backgroundColor(Color.Green)
			}
			if (this.targetView == 'CalendarPicker') {
				CalendarPicker({ hintRadius: 10, selected: new Date() })
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsCalendarPickerModifier)
			}
			if (this.targetView == 'Canvas') {
				Canvas(new CanvasRenderingContext2D(new RenderingContextSettings(true)))
					.backgroundColor('#FFFF00')
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsCanvasModifier)
			}
			if (this.targetView == 'FormLink') {
				FormLink({
					action: "router",
					abilityName: "EntryAbility",
					params: { 'message': 'testForRouter' }
				}) {
					Button("router event").width(120)
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsFormLinkModifier)
			}
			if (this.targetView == 'Hyperlink') {
				Hyperlink('https://example.com/', 'Go to the developer website') {
				}
					.commonStyle()
					.attributeModifier(this._dragPreviewOptionsHyperlinkModifier)
			}
			if (this.targetView == 'Span') {
				Text() {
					Span('Span1')
						.commonStyle()
						.attributeModifier(this._dragPreviewOptionsSpanModifier)
				}
			}
		}
		.width(this.parentWidth)
		.height(this.parentHeight)
		.backgroundColor(this.parentBackGroundColor || '#FFFF00')
		.key(this.parentComponentKey)
	}
}
