TT(RN,                        0x0p+0L,                        0x0p+0L,          0x0p+0, 0)
TT(RN,                       -0x0p+0L,                       -0x0p+0L,          0x0p+0, 0)
TT(RN,                            inf,                            NAN,          0x0p+0, INVALID)
TT(RN,                           -inf,                            NAN,          0x0p+0, INVALID)
TT(RN,                            NAN,                            NAN,          0x0p+0, 0)
